name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change 'main' to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16'  # Change to your Node.js version requirement

    - name: Install dependencies
      run: npm install  # Change if you use a different package manager

    - name: Build site
      run: npm run build  # Change to your build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT }}
        publish_dir: ./build  # Change to your build output directory